# Generated by Django 4.2.3 on 2024-02-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_verified',
        ),
    ]
